alias ..='cd ..'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias dsk='cd ~/Desktop'
alias hm='cd ~'
alias api='sudo apt-get install'
alias apr='sudo apt-get remove'
alias nba='nano ~/.bash_aliases'
alias vre='nano ~/.vimrc'
alias top="htop"
alias c='clear'
alias py="python3.5"
alias n="nikola"
alias gadd="git add *"
alias gcom="git commit -m"
alias gpom="git push -u origin master"
alias gr="byzanz-gui"
alias top='htop'
PS1="\[\e[01;31m\]┌─[\[\e[01;35m\u\e[01;31m\]]──[\[\e[00;37m\]${HOSTNAME%%.*}\[\e[01;32m\]]:\w$\[\e[01;31m\]\n\[\e[01;31m\]└──\[\e[01;36m\]>>\[\e[0m\]"
